### ISSUE TITLE
Error: gl returned null, this probably means that some dependencies are not installed. See README.

### ISSUE THREAD

**Issue by bigturtle88** [mifi/editly#181] opened 2022-02-09 16:31 UTC
Error: gl returned null, this probably means that some dependencies are not installed. See README.

I use a server from DigitalOcean.  
Ubuntu
node v12.13.1
ffmpeg version 4.2.4

on the local machine everything works. I can't figure out what addiction I should download. I have already installed xvfb.  I also looked at tips from other branches but it didn't help me. How do I understand and solve this problem.

**Comment by mifi** [comment] 2022-02-10 06:26
Duplicate of #33

**Closed by mifi** 2022-02-10 06:26 UTC
